spring:
  application.name: discord-bot
  profiles:
    default: local

cholog:
  github:
    token:
    api-version: 2022-11-28
  jda:
    token:
    guild-id:
    subscriptions:
      pr-merge:
        channel-id:
        allow-organizations:
          - next-step
          - cho-log
        allow-repositories:
          - java-ladder-func-playground
          - java-calculator-unit-playground
          - java-racingcar-simple-playground
          - java-lotto-clean-playground
          - spring-basic-roomescape-playground
          - spring-roomescape-playground
          - self-paced-react
        disallow-branches:
          - main
          - master
