name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Create application.yml
        env:
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
        run: |
          printf '%s\n' "$APPLICATION_YML" > src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew bootJar
